project: 
  type: website

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://shannonrankin.github.io/SECO-Pilot/" 
  repo-url: "https://github.com/shannonrankin/SECO-Pilot"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: content/images/wildlifeCommunity_ai.jpg
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://shannonrankin.github.io/SECO-Pilot/
        text: "Sound Ecology Pilot Studies"
      - icon: github
        href: https://github.com/shannonrankin/SECO-Pilot
        text: "Sound Ecology Pilot Studies Github Repository"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: content/methods-intro.qmd
        text: "Methods"
        contents: 
          - content/methods-recorders.qmd
          - content/methods-analysis.qmd
      - section: content/rails-intro.qmd
        text: "Pilot Study of Ridgeway's Rails in San Diego"
        contents:
          # - content/rails-dashboard.qmd
          - content/rails-data.qmd
          - content/rails-results.qmd
          - content/rails-future.qmd
      # - section: content/sci-intro.qmd
      #   text: "Pilot Study at San Clemente Islands"
      #     - content/sci-dashboard.qmd
      #     - content/sci-data.qmd
      #     - content/sci-results.qmd
      # - section: content/plus_betterscience
      # - text: "Better Science"
      #   contents: 
      #     - content/plus_communitySci.qmd
      #     - content/plus_openSci.qmd


        
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
